### ISSUE TITLE
Nasměrovat leanmapper.com na LeanMapper.github.io

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#12]
Myslím, že by bylo fajn doménu leanmapper.com nasměrovat na zdejší Github Pages. Všechen obsah z leanmapper.com by současný repozitář měl obsahovat (kromě API dokumentace, na to by se ale mohlo použít [codedoc](https://codedoc.pub/tharos/leanmapper)). Jediné co bude potřeba udělat, je nastavit přesměrování starých URL na nová - <del>na to připravuju [pull request](https://github.com/LeanMapper/LeanMapper.github.io/pull/16)</del> hotovo.

Co si o tom myslíte? @Tharos @castamir

**Comment by janpecha** [comment]
Pokud se nepletu, mělo by stačit:

1. nastavit v nastavení repozitáře doménu (https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)
2. upravit DNS záznamy pro doménu, aby mířili na GitHub (https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)

**Comment by castamir** [comment]
@Tharos mohl bys upravit DNS zaznamy prosim?

**Comment by Tharos** [comment]
Tak nastaveno (DNS). Tak uvidíme, jestli to zabere…

```
@ IN A 192.30.252.153
@ IN A 192.30.252.154
```

**Comment by janpecha** [comment]
@Tharos jen pro jistotu - na Wedosu je potřeba pro potvrzení změn v DNS ještě kliknout na tlačítko "Aplikovat změny", aby se změny reálně projevili. Osobně na to vždycky zapomenu.

**Comment by janpecha** [comment]
Tak doména `leanmapper.com` už míří na Github, akorát to hází 404.

A pak je ještě problém s doménou `www.leanmapper.com`, ta aktuálně míří na Ignum.

**Comment by Tharos** [comment]
Jj, akorát to dolazuji… :) S `leanmapper.com` jsi odhadl problém úplně přesně… Upravil jsem zónový soubor, uložil ho, ale pak samozřejmě nepotvrdil celou stránku… Musím říct, že Ignum má v téhle věci dost neohrabané rozhraní.

Proč má `www` varianta A na `217.31.49.32` zatím nevím, předpokládám, že na Ignumu jede přes stejný zónový soubor. Možná je to ještě otázka cache…

Na GitHubu je možná nastavená jenom varianta s `www`, tam bych to asi doladil, jakmile bude i `www` ukazovat na GitHub servery…

**Comment by janpecha** [comment]
Ono to vypadá, jako by byl pro `www` variantu nastaven CNAME záznam mířící na Ignum, není tam třeba někde nějaký zapomenutý?

**Comment by Tharos** [comment]
Ta doména je na Ignumu. Jen starý web běžel na Wedosu, a tak na něj byly nastavené NS záznamy. Teď už směřují zase na Ignum a A záznamy směřují na GitHub. Jen fakt zatím netuším, proč se `www` chová jinak… :)

![snimek obrazovky 2017-05-30 v 9 09 42](https://cloud.githubusercontent.com/assets/866325/26571877/149e78e8-4518-11e7-9b52-f880251ca0e2.png)

**Comment by janpecha** [comment]
Jj, vím, koukám na to přes `nslookup www.leanmapper.com ns1.ignum.cz`

Nemohl by být problém v tom řádku `* CNAME rimmer.core.ignum.cz.`, protože to je přesně ta adresa na kterou aktuálně míří `www` varianta.

EDIT: a nejen `www` varianta, všechny subdomény - např. test.leanmapper.com

**Comment by Tharos** [comment]
Tak to opravdu byla jenom cache, už vede na GitHub i `www`. Teď teda ještě nakonfit GitHub pages ;). Mám to udělat? Nebo na to někdo kouknete?

**Comment by janpecha** [comment]
Super. Asi bude nejlepší, když to uděláš ty, nemám přístup do nastavení repositáře.

**Comment by castamir** [comment]
já s tou změnou čekal na leanmapper.com - nechtěl jsem sejmout aktuální docku, o kterou se tak pěkně staráš :D

**Comment by janpecha** [comment]
Je to bezva :+1: díky oběma :)

**Comment by Tharos** [comment]
Nová docka je krásná a praktická, díky moc za ní! :)
