### ISSUE TITLE
Aktualizace Quick Startu

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#14]
Ahoj, připravuju PR s aktualizací Quick Startu a myslím, že by bylo fajn vytvořit pro quick start vlastní repozitář pod organizací LeanMapper. Z dokumentace by se na něj pak dalo odkazovat. Připravený ho mám [zde](https://github.com/janpecha/quick-start), takže by jen stačilo ho přesunout.

Lokálně mám připravenou i aktualizaci pro 3.1.1, ale tu bych rád poslal jako PR.

**Comment by janpecha** [comment]
Ping @castamir

**Comment by castamir** [comment]
stačí jednou ;)
promiň, že to visí na mě... nestíhám teď hodně věcí =/

**Comment by janpecha** [comment]
v pohodě, já jen aby to úplně nezapadlo :)

**Comment by castamir** [comment]
dnes odpoledne budu mit cas to poresit... diky za trpelivost...

**Comment by janpecha** [comment]
Díky

**Comment by castamir** [comment]
mel bys mit prava zapisu na quickstart, prosim over to

**Comment by janpecha** [comment]
funguje.

**Comment by janpecha** [comment]
@castamir do repozitáře leanmapper/quickstart jsem pushnul aktualizaci na poslední verzi LM a vytvořil PR na aktualizaci dokumentace (#17).

U quick startu bych potřeboval ještě jednu věc. Přidal jsem test, který testuje, jestli quick start dává očekávané výstupy, takže bych potřeboval povolit pro ten repozitář Travis ale mě to nejde. Buď nemám dostatečná práva, nebo jsem zapomněl někde něco povolit (ale nemůžu přijít na to co). Mohl bys to zkusit ty?

Díky.

**Comment by castamir** [comment]
@janpecha Propojil jsem github organizaci s Travis CI a zaplnul hook pro quickstart. Teoreticky by to mělo s dalším commitem fungovat.

**Comment by janpecha** [comment]
Funguje, díky.
