### ISSUE TITLE
push práva

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#19]
Ahoj, prosím o push práva, abych mohl v dokumentaci provádět drobné úpravy (překlepy, aktualizace changelogu pro vývojovou verzi,..), aniž bych tě pořád bombardoval pull requesty.

Díky.

**Comment by castamir** [comment]
Možná mi ta zpětná vazba chvíli trvá, ale myslím si, že tobě je ku prospěchu, když se ke tvé úpravě někdo vyjádří. Ikdyž je to jen dokumentace, nemyslíš?

**Comment by janpecha** [comment]
To určitě, ale vytvářet PR kvůli každému jednotlivému překlepu nebo opravě formátování, na které narazím, mi připadá zbytečné.
