### ISSUE TITLE
Repositář pro příklady

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#26]
@castamir Ahoj, můžeš prosím pod organizací LeanMapper vytvořit prázdný repozitář `examples` a povolit u něj Travis CI? Rád bych do něj umisťoval spustitelné příklady a odkazoval se na ně z dokumentace.

Díky.

**Comment by castamir** [comment]
Mám lepší nápad ;)

------
Nyní můžeš zakládat repozitáře a budeš mít rovnou write práva.

**Comment by janpecha** [comment]
Super, díky.
