### ISSUE TITLE
API dokumentace - codedoc.pub je mimo provoz

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#36]
Pro [API dokumentaci](http://leanmapper.com/cs/api/) jsme používali službu codedoc.pub - ta je už delší dobu nedostupná (viz https://github.com/nextras/orm/issues/288, https://pehapkari.slack.com/archives/C3RUH917D/p1522747111000401), bude tedy potřeba dokumentaci někam zmigrovat.

**Comment by castamir** [comment]
Dobré vědět.
