### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/LeanMapper.github.io#42]
Od května GitHub Pages přímo podporují HTTPS ([viz](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)). IMHO by bylo fajn to zapnout.

V našem případě by mělo stačit změnit IP adresy v `A` záznamech na:

* 185.199.108.153
* 185.199.109.153
* 185.199.110.153
* 185.199.111.153

[Info v dokumentaci](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider).

---

Po změně DNS záznamů a ověření funkčnosti je možné pro web zapnout vynucení HTTPS - viz [dokumentace](https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site).

---

Co myslíte? @Tharos @castamir

**Comment by janpecha** [comment]
@Tharos Ahoj, můžeš prosím změnit A záznamy pro doménu na následující IP adresy:

* 185.199.108.153
* 185.199.109.153
* 185.199.110.153
* 185.199.111.153

Původní IP adresy jsou prý už zastaralé.

Díky.

**Comment by castamir** [comment]
@Tharos

**Comment by Tharos** [comment]
Přes víkend to upravím. :)

**Comment by Tharos** [comment]
Tak v zónovém souboru upraveno. Kdyby bylo cokoliv dalšího zapotřebí z mé strany, dejte mi vědět.

**Comment by janpecha** [comment]
@Tharos díky!

@castamir možná ještě bude potřeba v nastavení repozitáře odebrat a znovu přidat doménu, aby došlo k vystavení HTTPS certifikátu. Mohl bys to prosím udělat? Nevím, kdo všechno má přístup do nastavení a kdo ne.

**Comment by castamir** [comment]
mrknu na to

**Comment by castamir** [comment]
<img width="708" alt="screen shot 2019-02-28 at 18 22 23" src="https://user-images.githubusercontent.com/1245190/53585287-d6168500-3b85-11e9-8211-0ec39986f1dd.png">

**Comment by janpecha** [comment]
@castamir díky
